[project]
name = "free_qr"
version = "0.1.0"
description = "Simple application for generating QR codes"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pypng>=0.20220715.0",
    "pyqrcode>=1.2.1",
]
